### ISSUE TITLE
Rocket.Chat doesn't build

### ISSUE THREAD

**Issue by Denommus** [svanderburg/node2nix#100]
When I try node2nix inside Rocket.Chat, `nix-build -A package` gives me the following error:

error: 'buildNodePackage' at /home/user/Projetos/rocket.chat-nixops/bundle/programs/server/node-env.nix:313:5 called without required argument 'version', at /nix/store/wba9bwq114wrqpkxj4y4323phry2jbyf-nixpkgs-18.09pre147772.d1ae60cbad7/nixpkgs/lib/customisation.nix:69:12

node2nix is 1.6.0, nix is 2.0.4, I downloaded Rocket.Chat from https://releases.rocket.chat/latest/download

I'm running node2nix from programs/server

**Comment by svanderburg** [comment]
@Denommus If you want to build a project from a `package.json` file then it should have at least a name and version attribute.

**Comment by Denommus** [comment]
That's ok.
