### ISSUE TITLE
node2nix fails with git submodule

### ISSUE THREAD

**Issue by aforemny** [svanderburg/node2nix#102]
Hi,
I am trying to use node2nix to create a package for parse-server. While this works fine, I encountered an issue with Git submodules.

The following works:
```sh
$ git clone github.com:parse-community/parse-server.git
$ cd parse-server
$ node2nix --nodejs-8 -l package-lock.json
$ nix-build -A package
```

The following does not work:
```sh
$ git submodule add github.com:parse-community/parse-server.git parse-server
$ cd parse-server
$ node2nix --nodejs-8 -l package-lock.json
$ nix-build -A package
```

The error with the second example is:
```
npm ERR! Error while executing:
npm ERR! /nix/store/15zsyygsmi9x6l05g3y5hq776plbfnp1-git-2.16.4/bin/git ls-remote -h -t ssh://git@github.com/mongodb-js/mongodb-tools.git
npm ERR!
npm ERR! fatal: Not a git repository: /nix/store/gbx1j0wjyd6pc97mymvpy9b9ifk9md5q-node-parse-server-2.8.2/lib/node_modules/parse-server/../.git/modules/parse-server
npm ERR!
npm ERR! exited with error code: 128
```

Let me know if I can provide further information or test something.

PS. Even with the first session, I get the `ENOGIT` error which I in each session fixed by manually editing the generated default.nix.

**Comment by svanderburg** [comment]
I added preliminary support for submodules in revision efa2c2a2f5ce0487fc428c167fd47052204c700c

**Comment by aforemny** [comment]
@svanderburg I can confirm that my original problem is resolved in that commit. Supplementing `node-pregyp`, I can build the parse-server package also from Git submodule. Thank you very much!

**Comment by svanderburg** [comment]
Closing this now. node2nix 1.7.0 was just released that provides Git sub module support.
