### ISSUE TITLE
Fails for project without 'version' field specification

### ISSUE THREAD

**Issue by kubek2k** [svanderburg/node2nix#104]
While trying to run a build of a project that had no `version` in the `package.json` file, it fails:
```
: /tmp/cli (master *%) $ nix-build -A package
error: 'buildNodePackage' at /private/tmp/cli/node-env.nix:313:5 called without required argument 'version', at /nix/store/ajmmfh21zjcma6qwlqxavrx1y0naklx3-nixpkgs-18.09pre146471.d7d31fea7e7/nixpkgs/lib/customisation.nix:74:12
```

I think it should (as in https://github.com/svanderburg/node2nix/issues/103), fail when the nix files are generated, when there is no version specified.

**Comment by svanderburg** [comment]
I added a name and version check in revision 91b2dd583cd127ff1a6f1447e7f1e4982980c584
