### ISSUE TITLE
404 Not Found when attempting to install backstopjs@3.5.6

### ISSUE THREAD

**Issue by jwoudenberg** [svanderburg/node2nix#107]
I'm trying to build `backstopjs` version `3.5.6` using `node2nix`, but am having some trouble getting it to work. Was hoping someone might understand what's going on and be able to help.

I run `node2nix` this way: `node2nix --include-peer-dependencies -i node-packages.json`

Then I add `backstopjs-3.5.6` to my `shell.nix` `buildInputs`. Unfortunately starting `nix-shell` doesn't work. It does some work for a bit, then crashes with the following error:

```
npm ERR! code E404
npm ERR! 404 Not Found: chromy@0.5.11

npm ERR! A complete log of this run can be found in:
npm ERR!     /private/tmp/nix-build-node-backstopjs-3.5.6.drv-0/.npm/_logs/2018-08-27T13_26_00_515Z-debug.log
builder for '/nix/store/wgp60i0dx7i6c08ap1pp945dj4mn8ziz-node-backstopjs-3.5.6.drv' failed with exit code 1
error: build of '/nix/store/wgp60i0dx7i6c08ap1pp945dj4mn8ziz-node-backstopjs-3.5.6.drv' failed
```

Any idea what I'm doing wrong?

**Comment by svanderburg** [comment]
I just tried deploying the package with this JSON file

```json
[
  { "backstopjs": "3.5.6" }
]
```

```bash
$ node2nix -i pkg.json
$ nix-build -A '"backstopjs-3.5.6"'
```

and it seems to work. The only reason why I think it may have failed is because one of the dependencies resolved to a package that was removed from registry, but this no longer seems to be the case.

**Comment by paulyoung** [comment]
I'm experiencing the same issue except that the error keeps alternating between 2 different packages. I tried both using @svanderburg's method above and there are no issues when doing it that way.

If I run the `nix-build` command that triggers the error with `-K` I can inspect the log:

```
npm ERR! A complete log of this run can be found in:
npm ERR!     /private/var/folders/yq/0b8xbm9j4yg8x3hjz_b3xvbh0000gn/T/<my derivation>.drv-1/.npm/_logs/2019-04-08T18_55_42_722Z-debug.log
```

In there I saw requests to `example.com`, which is apparently related to preventing impure downloads (?) (see https://github.com/svanderburg/node2nix/issues/32) and the `--offline` flag / `bypassCache` option:

https://github.com/svanderburg/node2nix/blob/c876bb8f8749d53ef759de809ce2aa68a8cce20e/nix/node-env.nix#L313

I got around this by doing the following:

```nix
let
  package = (import packagePath {
    nodejs = self.pkgs.nodejs;
    pkgs = self.pkgs;
  }).package.override {
    bypassCache = true;
  };
```

**Comment by svanderburg** [comment]
@paulyoung I think your issue looks similar, but it is also slightly different. Can you validate if this is still a problem for you with the latest node2nix version? If not, can you open a new issue? That makes it easier for me to track the problem and narrow down the origins of the problem.

I think issue can be closed since the problem with `backstopjs` has been identified, and solved.
