### ISSUE TITLE
The `NODE_PATH` supports multiple directories

### ISSUE THREAD

**Issue by CMCDragonkai** [svanderburg/node2nix#108]
Would it possible to do something similar to `PYTHONPATH` in that each Node package can add itself to the `NODE_PATH` and then you can Node dependencies like you do with Python dependencies in Nixpkgs?

**Comment by svanderburg** [comment]
Yes this is already possible. As a matter of fact, there is a setup hook for Node.js that already does this.

However, it is not a suitable replacement as a dependency substituter, for two reasons: first, NPM makes very specific assumptions about the nesting of node_modules/ folders which can't simulate by using this environment variable.

Second, there are in some scenarios so many NPM packages installed as dependencies that the corresponding environment variable will exceed the maximum length that the operating systems allows.

**Comment by CMCDragonkai** [comment]
I see, its scalability is an issue. You mentioned the nodejs setuphook already does this. But there are no nodejs libraries packaged in Nix, so is there nothing thay takes advantage of it?

**Comment by svanderburg** [comment]
@CMCDragonkai That's correct. The mechanism is there, but it isn't really used.

**Comment by svanderburg** [comment]
I guess the question has been answered, so closing this issue.
