### ISSUE TITLE
"node-" being added to the package name causes conflicts

### ISSUE THREAD

**Issue by jbwiv** [svanderburg/node2nix#110]
I am trying to install two packages: @types/google-apps-script and @google/clasp.

Installing either one by itself works, but upon trying to install the second package, regardless of which one, the other gets removed.

I noticed via nix-env -q that these packages are being installed as node-_at_google_slash_clasp-1.5.3 and node-_at_types_slash_google-apps-script-0.0.27. However, what happens is that node-env only parses up until "node-", per a discussion on irc, so nix-env recognized them both as packages named "node-". Consequently, it removes one and installs the other.

The solution is to not prefix with "node-", but something else nix doesn't treat specially.

**Comment by jbwiv** [comment]
Guys, any feedback on this? I'd really like to get it merged, as I'm having to maintain a local version of node2nix in the meantime. Please let me know. Thanks!

**Comment by svanderburg** [comment]
Patch has been integrated into the main branch. It will be part of the next release
