### ISSUE TITLE
nix-build generate lib without bin.

### ISSUE THREAD

**Issue by clojurians-org** [svanderburg/node2nix#116]
i run the following step to build electronic-wechat, but it result in library only.
so what i shoud do to generate the binary file to run.
```sh
git clone https://github.com/geeeeeeeeek/electronic-wechat
nix-shell -p nodePackages.node2nix
node2nix
nix-build -A package

[nix-shell:~/my-tmp/electronic-wechat]$ ls -l result
lrwxrwxrwx 1 larluo users 72 Oct 16 15:04 result -> /nix/store/9c9hi2h12q1xdlcvmnkdd2m56faq07xi-node-electronic-wechat-2.0.0

[nix-shell:~/my-tmp/electronic-wechat]$ ls -l result/
total 4
dr-xr-xr-x 3 root root 4096 Jan  1  1970 lib

```

**Comment by svanderburg** [comment]
I don't see any `bin` section in the `package.json` configuration that declares that this project ships any binaries. As a result, `node2nix` will not expose any, but I also believe that the vanilla NPM doesn't.

**Comment by svanderburg** [comment]
What you can also do is creating a wrapper script that starts the program. You can use an override in combination with a `postInstall` hook that generates the script and includes in the `bin/` sub folder of the package. Issue #125 is a similar problem I believe.
