### ISSUE TITLE
Purpose of node2nix unclear

### ISSUE THREAD

**Issue by timeyyy** [svanderburg/node2nix#124]
From reading the Readme and looking at some blogs/youtube videos i'm still not really sure why I would/if i should use this. Some text on why to use node2nix and the advantages of using node2nix over npm/yarn would be much appreciated.

**Comment by bsima** [comment]
You should use this if you are using [nix](https://nixos.org/nix).

**Comment by svanderburg** [comment]
I think it would not harm to add a bit of extra info what `node2nix` provides. I have extended the README with a few extra sentences: a9db6e3bb9b4ff7b4b36503602f2eedc06492776

**Comment by svanderburg** [comment]
I guess this issue is resolved, now that the README.md provides extra information.

**Comment by timeyyy** [comment]
Yup, thanks for that.
