### ISSUE TITLE
Implement a method that combines a package.json and an additional NPM package set that will appear in the PATH of the build environment

### ISSUE THREAD

**Issue by svanderburg** [svanderburg/node2nix#13]
For some Node.js development projects, it is a common habit that some dependencies are installed as devDependencies, whereas some other dependencies are installed globally.

For example, when using [grunt](https://github.com/gruntjs/grunt-cli), the CLI is typically installed globally, whereas the grunt plugins are provided through devDependencies.

Currently, there is no convenient way to automate this workflow apart from hacking two generated sets of expressions together.

Because this pattern is more common than I thought, I need to make a feature that conveniently automates it.

**Comment by svanderburg** [comment]
I have commited a first version in revision 5b5727bf542e5602c04bffca22fbb2ecf11da5f9

The section 'Adding additional/global NPM packages to a packaging process' in the README.md file describes how it works.

**Comment by svanderburg** [comment]
Closing the issue. It appears to be mature enough :)

**Comment by jluttine** [comment]
Why `supplement.json` needs to be a list? At least in the package I'm trying to compile, `devDependencies` are defined with version numbers similarly as normal dependencies in `package.json`. I would have expected that I could just copy paste that `devDependencies` section to `supplement.json` but I needed to convert it to a list, but I didn't need to that for `dependencies` in `package.json`. Why so?
