### ISSUE TITLE
Default to nodejs-10

### ISSUE THREAD

**Issue by jmackie** [svanderburg/node2nix#140]
`node2nix` currently targets nodejs-6 by default, which is EOL this month (https://github.com/nodejs/Release#release-schedule). Now might be a good time to bump the default to nodejs-10?

**Comment by samueldr** [comment]
Additionally, nodejs-6 [has been removed from master and release-19.03](https://github.com/NixOS/nixpkgs/commit/0e296d5fcdaf32dd113e49738dfba6216c01a8da).

**Comment by svanderburg** [comment]
@jmackie Although Node.js 10.x is the latest LTS release, I prefer to keep the default the oldest supported NPM release, to maximize version compatibility among versions.

Indeed, Node.js 6.x is EOL, so I should probably bump the default to 8.x, until the 8.x branch reaches EOL (which is by the end of December according to the documentation)

I will change the default to 8.x soon.

**Comment by svanderburg** [comment]
This commit makes 8.x the default version: 79754c17196230580ae55cde8c691ef91c872911

**Comment by svanderburg** [comment]
Closing this issue. node2nix has been upgrade in Nixpkgs and no longer introduces problems with Node.js 6.x missing: https://github.com/NixOS/nixpkgs/commit/18c2b52314f99e877aef5c44f8fdca0fe9ee4ea7
