### ISSUE TITLE
I'm just upset this repo still exists

### ISSUE THREAD

**Issue by loafbox** [svanderburg/node2nix#150]
There has to be a better way.
This can't be right, there's gotta be a better way.

**Comment by svanderburg** [comment]
@loafbox You made me curious. Could you elaborate?

**Comment by loafbox** [comment]
Just, I get it's a workaround imposed by immutable nix store.
So we're trying to nixify npm modules, and I'm wondering if we should just change settings on the npm nixpkg itself to use a writable path for it's modules so global install works natively.   Like
https://github.com/NixOS/nixpkgs/issues/3393#issuecomment-50330167

Would lose ability to rebuild, but I'd take a loss of nix functional awesomeness  for a standard webdev experience.  Worst case, is I think I would still have the same built tools to rebuild global modules if I needed.  But I'm not convinced even that's the best way so I'm just venting...
Lookin' for these better ways
Better ways, heyy! Better ways
Got me thinkin' bout better ways

**Comment by wmertens** [comment]
It's not trivial to do this.

pnpm uses an "immutable" store and some symlink tricks to combine built
modules with project-matching dependencies. It's been in development for
years and it's still buggy sometimes, like when you switch Node versions.

Wout.
