### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by juaningan** [svanderburg/node2nix#158]
Trying to package zigbee2mqtt dev branch it works but I need to workaround this error in `nix-build` last stage:

`npm ERR! cb() never called! lock using /build/.npm/_locks/s`

workaround: I add a ``|| true`` in `prepareAndInvoke` function final command in `node-env.nix`. 

If I run `npm install` manually ends well.
Any hint?

**Comment by charles-dyfis-net** [comment]
Does bumping the file descriptor limit for the nix-daemon service have any effect?

Something like (in `configuration.nix`):

```
systemd.services.nix-daemon.serviceConfig.LimitNOFILE = pkgs.lib.mkForce 262144;
```

...replacing the default hard FD limit of 4096, which npm hits in no time flat when given a large dependency tree.

I'm not at all confident that this is the only possible issue resulting in the symptom at hand (indeed, I'm quite certain it's not), but it's certainly *a* possible issue.

**Comment by juaningan** [comment]
It works! I had been struggling with FD limits before but not in nix-daemon service.

Have sense to PR app to nixpkgs upstream if failing in a standard environment?

**Comment by charles-dyfis-net** [comment]
I would certainly favor that nixpkgs PR. Even if it gets turned down, I expect the reasoning behind its rejection would be informative. :)

**Comment by juaningan** [comment]
Great I'll do then. Thanks for your help and opinion. :+1:
