### ISSUE TITLE
How can I use this to add a new package to nixpkgs?

### ISSUE THREAD

**Issue by siddharthist** [svanderburg/node2nix#16]
Sorry for my lack of experience here. On the (outdated) wiki, I found the following instructions:

> Short npm2nix usage explanation
> 
>     * Ensure npm2nix is available for use. One way is to install via nixpkgs -- nodePackages.npm2nix.
>     * Add a line to nixpkgs/pkgs/top-level/node-packages.json. Typically, the line will look something like: , "ionic" -- i.e. a comma followed by a string in double quotes.
>     * In nixpkgs/pkgs/top-level/, run: npm2nix node-packages.json node-packages-generated.nix
>     * After waiting for copious output to scroll by, try building: e.g. in the nixpkgs dir: nix-build -K -A nodePackages.ionic

Is there an analogous process for node2nix?

Sorry if I've missed some documentation, thanks for the help!

**Comment by svanderburg** [comment]
Yes, but it's slightly more complicated, because you need to generate two different kinds of package sets.

Installing node2nix from Nixpkgs is roughly the same step, e.g.:

```bash
$ nix-env -f '<nixpkgs>' -iA nodePackages.node2nix
```

Adding the package you want is similar too, but now you're supposed to change `pkgs/development/node-packages/node-packages.json`.

The most convenient way of regenerating the Nix expressions can be done by executing this script: `pkgs/development/node-packages/generate.sh`

**Comment by siddharthist** [comment]
After following your instructions, I get
```
$ nix-build -A emoj
error: attribute ‘emoj’ in selection path ‘emoj’ not found
```
even though it's been added by the script:
```
$ ag 'emoj[^i]'
pkgs/development/node-packages/node-packages.json
13:, "emoj"

pkgs/development/node-packages/node-packages-v5.nix
19897:  emoj = nodeEnv.buildNodePackage {
19898:    name = "emoj";
19899:    packageName = "emoj";
19902:      url = "https://registry.npmjs.org/emoj/-/emoj-0.3.0.tgz";
19981:      homepage = "https://github.com/sindresorhus/emoj#readme";

pkgs/development/node-packages/node-packages-v4.nix
22366:  emoj = nodeEnv.buildNodePackage {
22367:    name = "emoj";
22368:    packageName = "emoj";
22371:      url = "https://registry.npmjs.org/emoj/-/emoj-0.3.0.tgz";
22565:      homepage = "https://github.com/sindresorhus/emoj#readme";

pkgs/top-level/node-packages.json
64:, "emoj"
```
Do I have to add it somewhere else as well? 

Sorry if this is an easy question!

**Comment by svanderburg** [comment]
To build the package, you should change your working dir to the root of Nixpkgs, e.g.:

```bash
$ cd /path/to/nixpkgs
```

Then run:

```bash
$ nix-build -A nodePackages.emoj
```

By default, node packages are built again Node.js 4.4.x. To use a different nodejs version (e.g. 5.x), run the following command-line instruction:

```bash
$ nix-build -A nodePackages_5_x.emoj
```

**Comment by siddharthist** [comment]
@svanderburg Ah, I forgot the `nodePackages`! Thanks so much, I think I'll add what you've told me to the nixpkgs manual (Chapter 7) soon!
