### ISSUE TITLE
use "''${dontNpmInstall-}" instead of "$dontNpmInstall" in node-env.nix

### ISSUE THREAD

**Issue by cdepillabout** [svanderburg/node2nix#162]
There was a recent tree-wide update in nixpkgs that changed uses of `dont*` env vars:

https://github.com/NixOS/nixpkgs/commit/2811b032d639684d3983282e9d10d89f37d161d5

This also changed the `node-env.nix` file in nixpkgs:

https://github.com/NixOS/nixpkgs/commit/2811b032d639684d3983282e9d10d89f37d161d5#diff-30704c98a2c5c1c3f2129859e86e016c

However, when running [`generate.sh`](https://github.com/NixOS/nixpkgs/blob/3c3c59e0393d60d217fa392bbdf5900edb182a93/pkgs/development/node-packages/generate.sh), the correct `"''${dontNpmInstall-}"` gets reverted back to the incorrect `"$dontNpmInstall"`.

I think `node2nix` needs to be updated to use `"''${dontNpmInstall-}"`.

This came up in https://github.com/NixOS/nixpkgs/pull/74727.

**Comment by svanderburg** [comment]
This PR was integrated into master: 2a1be258b3eae837a575bd02dcd2170b0ce0ad88
