### ISSUE TITLE
bolt11 dependency - Error while gunzipping: Error: incorrect header check

### ISSUE THREAD

**Issue by fiksn** [svanderburg/node2nix#163]
A run of node2nix on https://github.com/BlueWallet/LndHub gives me:

> fetching local directory: ./. from .
> info attempt registry request try #1 at 11:59:48 AM
> http request GET http://registry.npmjs.org/babel
> http 200 http://registry.npmjs.org/babel
> info attempt registry request try #1 at 11:59:48 AM
> http request GET http://registry.npmjs.org/babel-cli
> http 200 http://registry.npmjs.org/babel-cli
> info attempt registry request try #1 at 11:59:48 AM
> http request GET http://registry.npmjs.org/babel-eslint
> http 200 http://registry.npmjs.org/babel-eslint
> info attempt registry request try #1 at 11:59:48 AM
> http request GET http://registry.npmjs.org/babel-polyfill
> http 200 http://registry.npmjs.org/babel-polyfill
> info attempt registry request try #1 at 11:59:48 AM
> http request GET http://registry.npmjs.org/babel-preset-env
> http 200 http://registry.npmjs.org/babel-preset-env
> info attempt registry request try #1 at 11:59:48 AM
> http request GET http://registry.npmjs.org/babel-preset-es2015
> http 200 http://registry.npmjs.org/babel-preset-es2015
> info attempt registry request try #1 at 11:59:48 AM
> http request GET http://registry.npmjs.org/babel-register
> http 200 http://registry.npmjs.org/babel-register
> info attempt registry request try #1 at 11:59:48 AM
> http request GET http://registry.npmjs.org/bignumber.js
> http 200 http://registry.npmjs.org/bignumber.js
**> fetching: https://github.com/bitcoinjs/bolt11
> Error while gunzipping: Error: incorrect header check**

a look into package.json under dependencies shows:

> "babel-register": "^6.26.0",
> "bignumber.js": "^8.0.1",
> **"bolt11": "https://github.com/bitcoinjs/bolt11",**
> "eslint": "^5.9.0",

is this format supported or what exactly is the matter here?

**Comment by svanderburg** [comment]
@fiksn The problem is that for arbitrary URL dependency specifiers, node2nix expect to retrieve a tarball for download, but that does not seem to be the case.

I just did a quick comparison with the vanilla NPM, and the vanilla NPM also does not seem to understand that dependency specifier.

If you change: `"https://github.com/bitcoinjs/bolt11"` to `bitcoinjs/bolt11` then it should work.

**Comment by fiksn** [comment]
Great, thanks for info.
