### ISSUE TITLE
npm fails to find some pre-downloaded dependency

### ISSUE THREAD

**Issue by pacien** [svanderburg/node2nix#179]
(https://github.com/NixOS/nixpkgs/pull/86599#discussion_r418974431)

For some reason, npm fails to find some dependency.

```
npm ERR! code ENOTCACHEDtchPackageMetaData error for eslint-K
npm ERR! request to https://registry.npmjs.org/eslint-utils failed: cache mode is 'only-if-cached' but no cached response available.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2020-05-02T15_46_11_921Z-debug.log

builder for '/nix/store/wkac3zzw316cx7mzh70ikw7j9ammcbl7-node_ldgallery-viewer-1.0.0.drv' failed with exit code 1
cannot build derivation '/nix/store/fqjisvda6pvd9lpj5rbapsqiwfslmliy-ldgallery-viewer.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/6whc0iz2qgzmv59nh7nlycv2l1h0ma33-ldgallery-1.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/6whc0iz2qgzmv59nh7nlycv2l1h0ma33-ldgallery-1.0.drv' failed
```

"eslint-utils" is however present (twice) in my generated node-packages.nix (https://github.com/NixOS/nixpkgs/blob/f5a643c6d0a2d05ca53bbe7cc9d1dd2a4fa5a667/pkgs/tools/graphics/ldgallery/viewer/node-packages.nix).

**Comment by svanderburg** [comment]
I need a bit of time to investigate this.

What I already did is I made clone of that Git repository myself, with the revision that is in the Nix expression.

Then I did:

```bash
cd viewer
node2nix -l package-lock.json -d
nix-build -A package
```

that seems to work.

**Comment by pacien** [comment]
Indeed it seems to work up to this step. It fails when I try to run `npm run build` in the `postInstall` phase here: https://github.com/NixOS/nixpkgs/pull/86599/files#diff-9de676ac1a4d333ac2f1568cffc2155cR9-R18

**Comment by juaningan** [comment]
similar problem here trying to build zigbee2mqtt:
```

ms@2.0.0 /nix/store/7v5nilq6lijjrxr173x71i6gv0a0889x-node_zigbee2mqtt-1.13.0/lib/node_modules/zigbee2mqtt/node_modules/follow-redirects/node_modules/ms
npm ERR! code ENOTCACHEDfetchPackageMetaData error forKK
npm ERR! request to https://registry.npmjs.org/tar-stream failed: cache mode is 'only-if-cached' but no cached response available.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2020-05-18T21_41_49_462Z-debug.log

builder for '/nix/store/5fg5813v3x983fjry3w1krkdswi3bz5w-node_zigbee2mqtt-1.13.0.drv' failed with exit code 1
error: build of '/nix/store/5fg5813v3x983fjry3w1krkdswi3bz5w-node_zigbee2mqtt-1.13.0.drv' failed

```

tar-stream is ok in /nix/store and generated node-packages.nix

**Comment by dysinger** [comment]
![image](https://user-images.githubusercontent.com/447/89110914-aca9fa80-d404-11ea-822b-c88d03b66514.png)

This is driving me crazy.

**Comment by svanderburg** [comment]
@dysinger Is your problem related to this issue (i.e. a failure because a predownloaded dependency is missing)?

If not, could you open a separate issue and describe your problem? That makes it easier for me to track the origins of the problems that I'm trying to solve.

If I look at your output, it looks like you have a failure because of a missing dependency.

**Comment by pacien** [comment]
It seems that my issue was due to the package-lock.json being out of sync due to a source override.
Making sure that everything is in sync makes the problem disappear. My bad!
