### ISSUE TITLE
RFC45 is not respected

### ISSUE THREAD

**Issue by veprbl** [svanderburg/node2nix#188]
For example, see
https://github.com/NixOS/nixpkgs/commit/d6c0115cee9507b1908e7e1b4ce08995e429611d
it has
```
homepage = https://mths.be/he;
```
but should be
```
homepage = "https://mths.be/he";
```

**Comment by svanderburg** [comment]
I just made a small adjustment in bfd517c1774ddb4ae1a459b8d96f1bc653a72bd1 that removes the usage of URL literals.

In the next release, all URLs will become strings

**Comment by svanderburg** [comment]
node2nix 1.9.0 was released that includes this fix. Moreover, the current Nixpkgs has been updated to use it.

This issue can be closed.
