### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by DamienCassou** [svanderburg/node2nix#191]
I'm trying to run on NixOS a very simple project that I created in Fedora. Running `yarn` in the project was working fine on Fedora but doesn't work anymore on NixOS:

```
$ yarn
error /home/cassou/Documents/projects/piechart/node_modules/canvas: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/cassou/Documents/projects/piechart/node_modules/canvas
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.18.0 | linux | x64
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
...
```

I decided to try `node2nix` instead of yarn but I wasn't luckier:

```
$ node2nix
...
$ nix-build -A package
...
> canvas@1.6.13 install /nix/store/nmy90ds3cdzwbq037p3fwqhw10gl6g14-node_piechart-0.1.0/lib/node_modules/piechart/node_modules/canvas
> node-gyp rebuild

./util/has_lib.sh: line 31: pkg-config: command not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/nix/store/m8cjih12nig9rmp8pfis9l6x5ypfm99m-nodejs-12.18.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.46
gyp ERR! command "/nix/store/m8cjih12nig9rmp8pfis9l6x5ypfm99m-nodejs-12.18.0/bin/node" "/nix/store/m8cjih12nig9rmp8pfis9l6x5ypfm99m-nodejs-12.18.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /nix/store/nmy90ds3cdzwbq037p3fwqhw10gl6g14-node_piechart-0.1.0/lib/node_modules/piechart/node_modules/canvas
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2020-06-22T16_32_40_369Z-debug.log
```

Can you please help me?

**Comment by svanderburg** [comment]
I suspect the line indicates what your problem is:

```bash
./util/has_lib.sh: line 31: pkg-config: command not found
```

Can you try creating an override that supplies `pkgconfig` as an additional native dependency? There is a section in the `README.md` that describes how to do this.

**Comment by DamienCassou** [comment]
Thank you for your answer @svanderburg. I have to admit I already read the README file and didn't quite understand it. If you want, I can open an issue will all my questions about the README file.

Regarding my issue, are you referring to the section "Adding unspecified dependencies"? I tried this `override.nix`:

```nix
{ pkgs ? import <nixpkgs> { inherit system;}, system ? builtins.currentSystem }:

let
  nodePackages = import ./default.nix {
    inherit pkgs system;
  };
in
nodePackages // {
  canvas = nodePackages.canvas.override {
    buildInputs = [ pkgs.pkgconfig ];
  };
}
```

I decided to override the canvas package because this is the one that appears in the error message above:

> Failed at the canvas@1.6.13 install script

Then, I tried `nix-build override.nix -A package` but the error message is still the same. I also tried to replace `canvas` with `piechart` (the name of my package) but this didn't have any impact.

In the README, I can read a different `nix-build` call:

```
$ nix-build override.nix -A floomatic
```

I replaced floomatic with piechart and canvas but this doesn't work either:

```
$ nix-build override.nix -A canvas
error: attribute 'canvas' missing, at /home/cassou/Documents/projects/piechart/override.nix:9:12
```

This error seems reasonable to me because `nodePackages` is basically what returns `default.nix`. This file basically returns `node-packages.nix` which returns an attribute set of `args`, `sources`, `tarball`, `package` and `shell`.

**Comment by svanderburg** [comment]
Can you try overriding it with:

```nix
{ pkgs ? import <nixpkgs> { inherit system;}, system ? builtins.currentSystem }:

let
  nodePackages = import ./default.nix {
    inherit pkgs system;
  };
in
nodePackages // {
  canvas = nodePackages.package.override {
    buildInputs = [ pkgs.pkgconfig ];
  };
}
```

Building it with `nix -build -A package` is the correct way to do it, because you have generated Nix expressions from a `package.json` file. When generating Nix expressions from a project's `package.json` file, the attribute that you need to refer to is called `package`.

**Comment by DamienCassou** [comment]
Your version didn't work but replacing `canvas = ...` with `package = ...` made it move forward. Thank you very much.

I got an error about missing `cairo` and I added it too. I now have a different error:
...
267 verbose lifecycle canvas@1.6.13~install: CWD: /nix/store/r214p2xmgbmkfwa3glp119qyh6iak48v-node_piechart-0.1.0/lib/node_modules/piechart/node_modules/canvas
268 silly lifecycle canvas@1.6.13~install: Args: [ '-c', 'node-gyp rebuild' ]
269 silly lifecycle canvas@1.6.13~install: Returned: code: 1  signal: null
270 info lifecycle canvas@1.6.13~install: Failed to exec install script
271 verbose stack Error: canvas@1.6.13 install: `node-gyp rebuild`
271 verbose stack Exit status 1
271 verbose stack     at EventEmitter.<anonymous> (/nix/store/ghydvqnwa9p14vd4r21szz2k0q6xasfq-nodejs-12.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
271 verbose stack     at EventEmitter.emit (events.js:315:20)
271 verbose stack     at ChildProcess.<anonymous> (/nix/store/ghydvqnwa9p14vd4r21szz2k0q6xasfq-nodejs-12.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
271 verbose stack     at ChildProcess.emit (events.js:315:20)
271 verbose stack     at maybeClose (internal/child_process.js:1021:16)
271 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
272 verbose pkgid canvas@1.6.13
273 verbose cwd /nix/store/r214p2xmgbmkfwa3glp119qyh6iak48v-node_piechart-0.1.0/lib/node_modules/piechart
274 verbose Linux 5.4.47
275 verbose argv "/nix/store/ghydvqnwa9p14vd4r21szz2k0q6xasfq-nodejs-12.18.1/bin/node" "/nix/store/ghydvqnwa9p14vd4r21szz2k0q6xasfq-nodejs-12.18.1/bin/npm" "--offline" "--nodedir=/nix/store/qxk03d438cf2py8d63khfji1xw3s4c71-node-sources" "rebuild"
276 verbose node v12.18.1
277 verbose npm  v6.14.5
278 error code ELIFECYCLE
279 error errno 1
280 error canvas@1.6.13 install: `node-gyp rebuild`
280 error Exit status 1
281 error Failed at the canvas@1.6.13 install script.
281 error This is probably not a problem with npm. There is likely additional logging output above.
282 verbose exit [ 1, true ]
```

**Comment by svanderburg** [comment]
Can you try to use `strace` with your build? I think this line:

```
Failed to exec install script
```

is what we need to diagnose. Strace can reveal you what script NPM is trying to execute. Something is wrong with that script -- maybe it does not exist, or it tries to execute a pre-built ELF binary that is not patched.

**Comment by DamienCassou** [comment]
I can't reproduce the trace above and I have another error message now. To facilitate debugging, I decided to create a script so anyone could reproduce anytime:

```bash
#! /usr/bin/env nix-shell
#! nix-shell -i bash -p bash nodePackages.node2nix nix
#! nix-shell --pure
#! nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/dc80d7bc4a244120b3d766746c41c0d9c5f81dfa.tar.gz

# nixos-unstable as of 2020-07-09:
export NIX_PATH="nixpkgs=https://github.com/NixOS/nixpkgs/archive/dc80d7bc4a244120b3d766746c41c0d9c5f81dfa.tar.gz"

set -e

function write_package_json() {
  cat > package.json <<EOF
{
  "name": "piechart",
  "version": "0.1.0",
  "dependencies": {
    "chartjs-node": "^1.7.1"
  }
}
EOF
}

function write_override_nix() {
  cat > override.nix <<EOF
let
  pkgs = import <nixpkgs> { };
  nodePackages = import ./default.nix {};
in
nodePackages // {
  package = nodePackages.package.override {
    buildInputs = with pkgs; [ pkgconfig cairo ];
  };
}
EOF
}

function main() {
  local tmp_dir
  tmp_dir=$(mktemp -d)

  echo "Executing script in ${tmp_dir}"
  cd "$tmp_dir"

  write_package_json
  write_override_nix
  node2nix --development
  nix-build override.nix -A package
}

main
```

**Comment by DamienCassou** [comment]
This results in

```
 2294 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
../src/Canvas.cc: In static member function 'static void Canvas::Initialize(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)':
../src/Canvas.cc:60:75: error: no matching function for call to 'v8::FunctionTemplate::GetFunction()'
   60 |   Nan::Set(target, Nan::New("Canvas").ToLocalChecked(), ctor->GetFunction());
      |                                                                           ^
...
...
make: *** [canvas.target.mk:127: Release/obj.target/canvas/src/Canvas.o] Error 1
make: Leaving directory '/nix/store/x09f902bw7qyh5m13l189dlkv83x8bji-node_piechart-0.1.0/lib/node_modules/piechart/node_modu
les/canvas/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/nix/store/ixv2g280131y7ji2f43mwqlk9y9s84ih-nodejs-12.18.2/lib/node_modules/npm/n
ode_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.50
gyp ERR! command "/nix/store/ixv2g280131y7ji2f43mwqlk9y9s84ih-nodejs-12.18.2/bin/node" "/nix/store/ixv2g280131y7ji2f43mwqlk9
y9s84ih-nodejs-12.18.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /nix/store/x09f902bw7qyh5m13l189dlkv83x8bji-node_piechart-0.1.0/lib/node_modules/piechart/node_modules/canvas
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2020-07-09T18_28_05_225Z-debug.log

builder for '/nix/store/mivw25cwpm7as9ij5qimk63cxk0ljsks-node_piechart-0.1.0.drv' failed with exit code 1
```

**Comment by svanderburg** [comment]
@DamienCassou I can't say for sure what you're problem is, but from looking at the output, it looks like it's a compilation problem caused by a V8 API incompatibility.

I have seen these kinds of issues in the past -- for example, if you try to compile a module whose native bindings have not been updated to work with a newer version of Node.js.

I can see that you're currently using Node.js 12.x. What happens if you downgrade Node.js to an older version, e.g. 10.x? Or what happens if you try another version Node.js? or yet an even older or newer version?

Maybe the `canvas` dependency is outdated and has a newer version that fixes the compatibility problem. Another option would be to try to update it somehow, if that's possible.

**Comment by DamienCassou** [comment]
Thank you very much, that was it. Using node 10 from nixos-19.09 fixed the build. Here is the script.

```nix
#! /usr/bin/env nix-shell
#! nix-shell -i bash -p bash nodePackages.node2nix nix
#! nix-shell --pure
#! nix-shell -I nixpkgs=channel:nixos-19.09

# nixos-unstable as of 2020-07-09:
export NIX_PATH="nixpkgs=channel:nixos-19.09"

set -e

function write_package_json() {
  cat > package.json <<EOF
{
  "name": "piechart",
  "version": "0.1.0",
  "dependencies": {
    "chartjs-node": "^1.7.1"
  }
}
EOF
}

function write_override_nix() {
  cat > override.nix <<EOF
let
  pkgs = import <nixpkgs> { };
  nodePackages = import ./default.nix {};
in
nodePackages // {
  package = nodePackages.package.override {
    buildInputs = with pkgs; [ pkgconfig cairo ];
  };
}
EOF
}

function main() {
  local tmp_dir
  tmp_dir=$(mktemp -d)

  echo "Executing script in ${tmp_dir}"
  cd "$tmp_dir"

  write_package_json
  write_override_nix
  node2nix --development --nodejs-10
  nix-build override.nix -A package
}

main
```
