### ISSUE TITLE
New node2nix release?

### ISSUE THREAD

**Issue by delroth** [svanderburg/node2nix#210]
I'm trying to package some javascript webui which requires nodejs 14.x. I see there was a change to node2nix to add -14 but this hasn't been released yet. When is the next release scheduled?

**Comment by svanderburg** [comment]
There will be one very soon -- what remains is reviewing 2 more pull requests (for one I'm still awaiting feedback), and a very subtle/small change..

If you want to use the development version, then you can already use by cloning this repo and running:

```bash
$ nix-env -f release.nix -iA build.x86_64-linux
```

**Comment by svanderburg** [comment]
A new released was published yesterday.

I have also started porting everything over in Nixpkgs. The WIP pull request can be found here: https://github.com/NixOS/nixpkgs/pull/110545

Most of it works -- there seem to be two packages that I have problems with updating

**Comment by svanderburg** [comment]
We have managed to successfully update Nixpkgs, with the new node2nix 1.9.0, so this issue can be closed.
