### ISSUE TITLE
Update utillinux to util-linux

### ISSUE THREAD

**Issue by mweinelt** [svanderburg/node2nix#213]
In https://github.com/NixOS/nixpkgs/pull/104776/ `utllinux` was renamed to `util-linux`.

On nixos unstable this leads to the following error when trying to build the package:

```
error: anonymous function at ./pkgs/development/node-packages/node-env.nix:3:1 called without required argument 'util-linux', at ./pkgs/servers/zigbee2mqtt/node.nix:8:13
```

Replacing `utillinux` as described fixes that.

**Comment by svanderburg** [comment]
Hmm ok, I probably need to implement a reference to `utillinux` in such a way that it works with both the latest stable version of Nixpkgs as well as the latest master version.

**Comment by svanderburg** [comment]
Revision 52436bba120d78f33bf7432c7147078b2de1b264 (that I just committed) should fix the problem in a backwards compatible way -- node2nix should work with both the master branch and the 20.09 branch of Nixpkgs

**Comment by svanderburg** [comment]
node2nix 1.9.0 was released that fixes the issue (it supports both the old and new scenario). Nixpkgs was updated a couple of days ago, so this issue can be closed.
