### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by lovesegfault** [svanderburg/node2nix#222]
A number of small but meaningful fixes have landed since the last release, it'd be nice if a new release was cut with them included.

This would be especially useful for nixpkgs, where the current editorconfig checks prevent any PR's that update node packages from landing.

**Comment by svanderburg** [comment]
Yes I'm almost ready to release the new version. There's one issue I'm at the moment still investigating, but when that is done I'll publish a new release.

In the meantime, you can already help me by testing some of the packages you rely on.

**Comment by svanderburg** [comment]
#207 is still a blocker

**Comment by svanderburg** [comment]
Release done. I have started the following PR to update Nixpkgs: https://github.com/NixOS/nixpkgs/pull/110545

Almost everything seem to work, but there are some weird packages for which I could use some help (see comments in the PR)

**Comment by svanderburg** [comment]
Nixpkgs was updated a couple of days ago, so this issue can be closed.

**Comment by lovesegfault** [comment]
Thank you!
