### ISSUE TITLE
node-env.nix is no longer generated

### ISSUE THREAD

**Issue by alyssais** [svanderburg/node2nix#223]
I was attempting to update node2nix in Nixpkgs to HEAD, because not having #216 is making things difficult for people.  But node2nix doesn’t seem to be generating node-env.nix any more, so attempting to update it break nodePackages.

git bisect tells me 5677047 is the commit that changed this.

**Comment by svanderburg** [comment]
This is indeed a very weird bug. If I modify the `node-packages.json` file in the Nixpkgs collection to only contain a very small sub set of packages then the generation does seem to work.

I suspect when there is a package that depends on a dependency that ships with a lock file, the generation terminates at the wrong place.

Including lock files of dependencies was recently integrated from a pull request made by somebody else but me, but unfortunately there is no test coverage for this yet. This is still a blocker for the next release of node2nix. I'm currently investigating the situation and working on a test scenario myself.

**Comment by svanderburg** [comment]
The most likely candidate appears to be a dependency from a remote HTTP site containing a tarball with lock file

**Comment by svanderburg** [comment]
After a tough debugging session I think I have managed to identify and fix the problem.

I just applied a fix c98ab6506105ad6d9ba47b814ffde65e22ab320e that fixes a race condition. I just managed to successfully regenerate the packages.

You can also try it yourself -- however, if you intend to update Nixpkgs with the latest master version: I'm currently still validating the new functionality that examines the lockfiles provided by the dependencies as well. I cannot yet guarantee that this new functionality is free of problems.

**Comment by svanderburg** [comment]
node2nix 1.9.0 was released that fixes this issue. Moreover, Nixpkgs was updated a couple of days ago, so this issue can be closed.
