### ISSUE TITLE
Unable to locate X11 header file

### ISSUE THREAD

**Issue by mattmelling** [svanderburg/node2nix#225]
I am trying to build a package that depends on `robotjs`, which in turn has a dependency on `libX11`. Following the `floomatic` example, my `override.nix` looks like this:
```
{ pkgs ? import <nixpkgs> {
  inherit system;
}, system ? builtins.currentSystem }:
let
  nodePackages = import ./node-composition.nix {
    inherit pkgs system;
  };
in
nodePackages // {
  "robotjs-0.6.0" = nodePackages."robotjs-0.6.0".override {
    buildInputs = [ pkgs.xorg.libX11 ];
  };
}
```

However `nix-build override.nix` fails with:

```> robotjs@0.6.0 install /nix/store/vh19l1gkbssgp30ik8va81pzn10mjavq-node_lunchpad-0.4.0/lib/node_modules/lunchpad/node_modules/robotjs
> prebuild-install || node-gyp rebuild

make: Entering directory '/nix/store/vh19l1gkbssgp30ik8va81pzn10mjavq-node_lunchpad-0.4.0/lib/node_modules/lunchpad/node_modules/robotjs/build'
  CXX(target) Release/obj.target/robotjs/src/robotjs.o
cc1plus: warning: command line option '-Wbad-function-cast' is valid for C/ObjC but not for C++
In file included from ../src/keypress.h:6,
                 from ../src/robotjs.cc:7:
../src/keycode.h:114:10: fatal error: X11/Xutil.h: No such file or directory
  114 | #include <X11/Xutil.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [robotjs.target.mk:126: Release/obj.target/robotjs/src/robotjs.o] Error 1
```

Is this an issue with how I am specifying the dependency on `libX11` or something else?

**Comment by wmertens** [comment]
You need libX11.dev

**Comment by mattmelling** [comment]
@wmertens Thanks, however that doesn't seem to help node-gyp find Xutil.h if I swap out pkgs.xorg.libX11 for pkgs.xorg.libX11.dev.

**Comment by mattmelling** [comment]
Ok, I came back to this after some time away from it (amazing how that helps), and found that providing the dependency to robotjs did not work, but it worked when I supplied it to package instead. Thanks for the suggestion.

**Comment by jeff-hykin** [comment]
hey @mattmelling could you give a bit more info? I've got the same issue but I'm not sure what you mean with `when I supplied it to package instead`
