### ISSUE TITLE
Node2nix fails to install with nodejs-15 and nodejs-16

### ISSUE THREAD

**Issue by chaoflow** [svanderburg/node2nix#236]
shell.nix
```
with import <nixpkgs> {};

let
    nodejs = nodejs-14_x;  # STILL WORKS
    # nodejs = nodejs-15_x;  # FAILS
    # nodejs = nodejs-16_x;  # FAILS
    nodePackages = pkgs.nodePackages.override {
      inherit nodejs;
    };

in

stdenv.mkDerivation rec {
  name = baseNameOf (builtins.getEnv "PWD");
  buildInputs = [
    nodejs
    nodePackages.node2nix
  ];
}
```

Failure for nodesjs-15 and nodejs-16 is identical.
```
nix-shell
...
rebuilt dependencies successfully
npm ERR! code ENOTCACHEDlTree buildDeps1ms
npm ERR! request to https://registry.npmjs.org/jsdoc failed: cache mode is 'only-if-cached' but no cached response available.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2021-05-03T17_01_25_614Z-debug.log

builder for '/nix/store/ymrcv3axb8rfmvi1pk3yf03wbjgk505b-node_node2nix-1.9.0.drv' failed with exit code 1
error: build of '/nix/store/ymrcv3axb8rfmvi1pk3yf03wbjgk505b-node_node2nix-1.9.0.drv' failed
```

**Comment by chaoflow** [comment]
``npm install -g`` with nodejs-16.0.0 and npm-7.10.0 installs successfully. However there are no ``--nodejs-15`` and ``--nodejs-16`` switches yet. See also #232

**Comment by turboMaCk** [comment]
I'm getting the same errors even when passing old nodejs version. Practically everything in `elmPackages` that uses node2nix is broken because of this issue in master and unstable in nixpkgs. This is script we use to generate nix expressions https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/elm/packages/generate-node-packages.sh

Is this the known issue?

**Comment by turboMaCk** [comment]
update: got fix for elmPackages - https://github.com/NixOS/nixpkgs/pull/152764 we were overriding nodejs by what ever we get passed in as `nodejs` attribute from nixpkgs - that was the reason for build failing.

**Comment by toastal** [comment]
However, Node 14.x won't be LTS forever. This will remain an issue, especially as newcomers are looking to use the latest LTS or newer.

**Comment by svanderburg** [comment]
The current release supports newer versions. However, Nixpkgs is still referring to the previous release.

I'm still in the process of updating Nixpkgs, which is quite a bit of work: https://github.com/svanderburg/node2nix/issues/274

If you want to help, try repeating the process. So start with a node2nix installed without the script, then update the packages, then try to update all packages that are not in `node-packages.json`. This is actually the most tedious part.

**Comment by andersk** [comment]
The current release still doesn’t work with newer Node.js. `node2nix` reconstructs a `package-lock.json` file with  `lockFileVersion: 1`; the newer `npm` tries to convert it to `lockFileVersion: 2`, and fails for lack of network access in the Nix sandbox. This is the error message originally reported in this issue.

```console
$ echo '["chalk"]' > node-packages.json

$ npx node2nix@1.11.0 --version
node2nix 1.11.0

$ npx node2nix@1.11.0 --nodejs-16 --input node-packages.json
info attempt registry request try #1 at 6:09:03 PM
http request GET https://registry.npmjs.org/chalk
http 200 https://registry.npmjs.org/chalk

$ nix-build
this derivation will be built:
  /nix/store/vxhbcl0nbz57yb2h8nasd95cryxglxaq-chalk-5.0.1.drv
building '/nix/store/vxhbcl0nbz57yb2h8nasd95cryxglxaq-chalk-5.0.1.drv'...
unpacking sources
patching sources
configuring
no configure script, doing nothing
building
installing
unpacking source archive /nix/store/dld45vw4jhv1scs7j6mz448ljwf41b1p-chalk-5.0.1.tgz
pinpointing versions of dependencies...
patching script interpreter paths in .
No package-lock.json file found, reconstructing...
rebuilt dependencies successfully
npm WARN old lockfile marborist:ctor Completed in 0ms
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm ERR! code ENOTCACHED
npm ERR! request to https://registry.npmjs.org/@types%2fnode failed: cache mode is 'only-if-cached' but no cached response is available.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2022-04-23T01_09_41_970Z-debug-0.log

error: builder for '/nix/store/vxhbcl0nbz57yb2h8nasd95cryxglxaq-chalk-5.0.1.drv' failed with exit code 1;
       last 10 log lines:
       > npm WARN old lockfile so supplemental metadata must be fetched from the registry.
       > npm WARN old lockfile
       > npm WARN old lockfile This is a one-time fix-up, please be patient...
       > npm WARN old lockfile
       > npm ERR! code ENOTCACHED
       > npm ERR! request to https://registry.npmjs.org/@types%2fnode failed: cache mode is 'only-if-cached' but no cached response is available.
       > 
       > npm ERR! A complete log of this run can be found in:
       > npm ERR!     /build/.npm/_logs/2022-04-23T01_09_41_970Z-debug-0.log
       > 
       For full logs, run 'nix log /nix/store/vxhbcl0nbz57yb2h8nasd95cryxglxaq-chalk-5.0.1.drv'.
```

**Comment by dotlambda** [comment]
> So start with a node2nix installed without the script, then update the packages, then try to update all packages that are not in `node-packages.json`. This is actually the most tedious part.

We could keep the old `node-env.nix` (or better: move it somewhere and change all references to it) so we can update `nodePackages` only.

**Comment by snawaz** [comment]
Any update on this?

I'm facing exactly the same issue. With `nodejs-14_x`, I dont get this error (though I see some other issue) but with `nodejs-16_x;` I see the same `npm WARN old lockfile The package-lock.json file was created with an old version of npm` issue.

**Comment by snawaz** [comment]
@chaoflow 

Which version/commit of `nixpkgs` did you use btw?
