### ISSUE TITLE
Import from derivation?

### ISSUE THREAD

**Issue by rvl** [svanderburg/node2nix#237]
Hi Sander,

I was wondering, do you know if anyone has tried and succeeded with importing a derivation containing the generated outputs of `node2nix` (IFD for short)?

In theory, it seems like it would work well if the project has a `package-lock.json` - because all NPM dependencies should be convertible to fixed-output derivations.

Cheers,

Rodney

**Comment by ryneeverett** [comment]
Yes. See https://github.com/svanderburg/node2nix/issues/149#issuecomment-701417862.

**Comment by rvl** [comment]
Thanks @ryneeverett, OK. I wasn't sure from the comment whether the attempt was actually successful, but looking into it more closely, it seems so: https://github.com/MatrixAI/TypeScript-Demo-Lib/blob/master/utils.nix

**Comment by ryneeverett** [comment]
Yes, I've been able to replicate that approach successfully in other contexts.

**Comment by ryneeverett** [comment]
You may want to consider https://github.com/tweag/npmlock2nix for IFD though. I haven't used it but it appears better designed for that use case.
