### ISSUE TITLE
Release with strippedName fix

### ISSUE THREAD

**Issue by frontsideair** [svanderburg/node2nix#24]
Thanks for merging the strippedName fix, that was crucial for us. Will you be releasing a new version with said fix anytime soon? I'm using node2nix in development from source so it's not a huge deal but it'd be nice to have it on nixpkgs too.

If there's no blocker and it's straightforward, I may do it too.

**Comment by svanderburg** [comment]
I will do so in a few days. Currently I'm still abroad with only limited Internet access, but I'll head back home tomorrow.

**Comment by frontsideair** [comment]
That's good to hear, no need to hurry though.

**Comment by frontsideair** [comment]
Any update on this?

**Comment by svanderburg** [comment]
Just released version 1.1.1 and regenerated the package set in Nixpkgs
