### ISSUE TITLE
[Help] Install Packages into System

### ISSUE THREAD

**Issue by dustinlacewell** [svanderburg/node2nix#245]
There is an NPM package called `nx` which provides the `nx` binary (it is a monorepo utility).

In my `environment.systemPackages` I have `nodejs-14_x` and `nodePackages.pnpm` and able to use them without issue.

I have placed the following into `node-packages.json`:
```
[ `nx` ]
```

I then ran `node2nix -i node-packages.json` which produced `node-packages.nix` and `node-env.nix`.

My question is, how do I utilize these outputs and integrate them into my system config so that `nx` is an available binary in the profile? Would anything special need to be done to ensure that the `nx` package is "integrate" into the node environment provided by `nodejs-14_x` like is done with `nodePackages.pnpm`?

**Comment by dustinlacewell** [comment]
I figured it out.

Something like the following gets the job done:
```nix
let
  nodeEnv = with pkgs; callPackage ./node-env.lib.nix {
    inherit lib stdenv nodejs python2 pkgs libtool runCommand writeTextFile;
  };
  nxPkgs = with pkgs; callPackage ./nx.lib.nix {
    inherit nodeEnv fetchgit nix-gitignore lib;
  };
in {
  environment.systemPackages = with pkgs; [
    nodejs-14_x nodePackages.pnpm nxPkgs.nx
  ]
}
```

**Comment by Artturin** [comment]
here's my solution
```
[
    "nx"
]
```
in mynode/node-packages.json

run `node2nix -i node-packages.json` in mynode and then add to your config
```
  nixpkgs.overlays = [
      (self: super: {
        mynodePackages = super.dontRecurseIntoAttrs (super.callPackage ./testjs/default.nix {
          nodejs = super.nodejs;
        });
      })
    ];
``` 
and `mynodePackages.nx` in systemPackages
