### ISSUE TITLE
Python version used by node

### ISSUE THREAD

**Issue by FRidh** [svanderburg/node2nix#25]
I'm working on migrating Nixpkgs to Python 3 as default. Not all packages support 3.x yet, and in those cases `python2` needs to be explicitly passed in. I will make the changes in the Nixpkgs repo, even on the generated files, but you will need to explicitly use `python2` here. Furthermore, I will add `passthru.python` to `nodejs` so I recommend `nodeEnv` uses that instead. That way we can guarantee the same version of Python is used.

Branch: https://github.com/NixOS/nixpkgs/tree/python3
PR: https://github.com/NixOS/nixpkgs/pull/19626
Issue: https://github.com/NixOS/nixpkgs/issues/18185

**Comment by svanderburg** [comment]
The only solution I have in mind is that we must make the python version used configurable so that we can retain compatibility with both the master and latest stable branches.

**Comment by svanderburg** [comment]
Since rev aabfd15aed70843a5aae1f20eaff93524046bbf4, we now explicitly refer to `python2`
