### ISSUE TITLE
allow to set package version

### ISSUE THREAD

**Issue by milahu** [svanderburg/node2nix#257]
some `package.json` files have no `version` field

```
$ node2nix
Mandatory version attribute is missing in package.json
```

lets allow to set the package version in `node2nix`

```
$ node2nix --package-version 1.2.3
```

why?
a package can consist of multiple subpackages,
and the package version is declared only once in the central `package.json`
and the subpackages have no version in their `package.json`

**Comment by milahu** [comment]
> a package can consist of multiple subpackages

to deduplicate all the dependencies, we can [merge multiple package.json files](https://stackoverflow.com/questions/19529688/how-to-merge-2-json-objects-from-2-files-using-jq) into one

```
jq -r --slurp '.[0] * .[1] * .[2]' a/package.json b/package.json c/package.json >package.json
```

**Comment by svanderburg** [comment]
I implemented a fix in https://github.com/svanderburg/node2nix/commit/5ebb644c37fb3b6ecdd2a21692381d2fbd6ccd7a

In the latest development version, the `version` attribute should now be optional

**Comment by milahu** [comment]
thanks : )
