### ISSUE TITLE
npm packages with a dot in their name yield an error

### ISSUE THREAD

**Issue by elmarsto** [svanderburg/node2nix#265]
The following code, which works for most npm packages, fails when the package name is 'nb.sh'

```
node2nix -i <(echo '["nb.sh"]')
nix-env -f ./default.nix -iA nb.sh
```
Specifically, the above generates the following error:

```
info attempt registry request try #1 at 8:23:50 PM
http request GET https://registry.npmjs.org/nb.sh
http 200 https://registry.npmjs.org/nb.sh
error: attribute 'nb' in selection path 'nb.sh' not found
```

The error is easily solved by editing `node-packages.nix` and `9g:s/nb\.sh/nb-sh/` (in `vim`), and then doing `nix-env -f ./default.nix -A nb-sh` (note the hyphen,) but it should not in the first place happen.

**Comment by svanderburg** [comment]
This is a think a Nix expression language quirk people have to take into account :)

**Comment by svanderburg** [comment]
I close this issue, because I believe the above description should solve the problem. If it remains a problem, then please reopen this issue.
