### ISSUE TITLE
node2nix and nixpkgs seem disagree on git

### ISSUE THREAD

**Issue by ip1981** [svanderburg/node2nix#27]
`node2nix/1.1.0`, `nixpkgs >= 16.09`. AFAIK, nixpkgs' builders remove all of `.git*`

```
...
output path ‘/nix/store/c6w7nwapx9qynvbwx960w0hwfxb1hs5c-jquery-f852e63’ has r:sha256 hash ‘18wjafary7q10jaqq07xnzrnji1vb4db3r390sgpjv3dbrqsf4k2’ when ‘0kn0cxkl3j31bj0q6zbdzz3df68flyj12yhsx7gaclr7p15xp0rx’ was expected
...
# ls -lh /nix/store/c6w7nwapx9qynvbwx960w0hwfxb1hs5c-jquery-f852e63/.git*
-rw-r--r-- 1 pashev users  26 ноя 27 14:07 /nix/store/c6w7nwapx9qynvbwx960w0hwfxb1hs5c-jquery-f852e63/.gitattributes
-rw-r--r-- 1 pashev users 178 ноя 27 14:07 /nix/store/c6w7nwapx9qynvbwx960w0hwfxb1hs5c-jquery-f852e63/.gitignore
-rw-r--r-- 1 pashev users 171 ноя 27 14:07 /nix/store/c6w7nwapx9qynvbwx960w0hwfxb1hs5c-jquery-f852e63/.gitmodules
```

**Comment by svanderburg** [comment]
In Nixpkgs 16.03, the default behaviour of fetchgit is that all files having a .git* prefix are recursively removed. In Nixpkgs 16.09 this behaviour has changed -- now only the .git folder in the base dir is removed.

I'm trying to reproduce this issue with Nixpkgs 16.09 and the master branch, but for me installing jquery seems to work fine, if I create a simple JSON file that refers to the latest git clone of jquery.

Can you provide me some more details how I can reproduce your scenario?

**Comment by ip1981** [comment]
`node2nix` `+` kibana's `package.json` :)

**Comment by svanderburg** [comment]
It appears that the implementation of fetchgit has changed again -- now there is some added functionality that configures a default git branch name (whose value corresponds to: fetchgit). As a result, the computed hashes will differ.

It seems that I have to change the implementation again to take this into account.

**Comment by svanderburg** [comment]
This is no longer a problem in the latest version
