### ISSUE TITLE
Generated package sets do not quote homepage

### ISSUE THREAD

**Issue by xaverdh** [svanderburg/node2nix#270]
See https://github.com/NixOS/nixpkgs/pull/145260#pullrequestreview-802058235 for where this came up.
According to RFC 0045, unquoted urls are considered deprecated and should no longer be used.

**Comment by xaverdh** [comment]
ah I think newer versions of node2nix do quote urls, right?

**Comment by xaverdh** [comment]
ah the commit is https://github.com/svanderburg/node2nix/commit/bfd517c1774ddb4ae1a459b8d96f1bc653a72bd1#diff-ad64440a19a048c0ea247d2f35e29ddc27b3395db3176b486a65e3349644b138, closing

**Comment by svanderburg** [comment]
Yes this was already changed quite some time ago. I guess that commit may have been generated by an older version.
