### ISSUE TITLE
Supplements support doesn't work in nix-shell?

### ISSUE THREAD

**Issue by k0001** [svanderburg/node2nix#29]
It looks like the supplements support in #13 doesn't cover supplement dependencies for `nix-shell`. For example, I have a project that uses `gulp-cli` (a `grunt-cli` like thing) in a `supplement.json` file, and builds just fine with `nix-build default.nix -A package`, but if I try to run `nix-shell default.nix -A shell` and then use `gulp-cli` inside that shell it fails:

`default.nix`:

```nix
{ system ? builtins.currentSystem
, pkgs ? import <nixpkgs> { inherit system; }
, nodejs ? pkgs."nodejs-5_x"
}:
let
  globalBuildInputs = pkgs.lib.attrValues (import ./supplement.nix {
    inherit nodeEnv;
    inherit (pkgs) fetchurl fetchgit;
  });
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv python utillinux runCommand writeTextFile;
    inherit nodejs;
  };
  nodePackages = import ./node-packages.nix {
    inherit (pkgs) fetchurl fetchgit;
    inherit nodeEnv globalBuildInputs;
  };
in
nodePackages // {
  package = nodePackages.package.override (oldAttrs: {
    postInstall = "gulp build";
  });
}
```

I generated the Nix files using this call to `node2nix` (I'm not sure what `--include-peer-dependencies` is for, I tried with and without it just in case):

```
node2nix \
  --development \
  --include-peer-dependencies \
  --nodejs-5 \
  --input ./package.json \
  --output ./node-packages.nix \
  --composition ./default.nix \
  --node-env ./node-env.nix \
  --supplement-input ./supplement.json \
  --supplement-output ./supplement.nix
```

Running `nix-build default.nix -A package` works fine, but manually running `gulp build` inside `nix-shell default.nix -A shell` fails due to some `babel` related dependencies being missing:

```
$ gulp build
[04:15:17] Failed to load external module babel-register
[04:15:17] Failed to load external module babel-core/register
[04:15:17] Failed to load external module babel/register
/home/k/foo/template-build/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import config from './config.json';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at execute (/nix/store/wnaljiagzbjdf4kr7s2f8hgyjss16234-node-gulp-cli-1.2.2/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:24:18)
    at Liftoff.handleArguments (/nix/store/wnaljiagzbjdf4kr7s2f8hgyjss16234-node-gulp-cli-1.2.2/lib/node_modules/gulp-cli/index.js:149:63)
```

According to `strace`, `gulp` seems to be looking for this `babel` stuff inside a `node_modules` folder that effectively does not contain anything related to `babel`.

**Comment by k0001** [comment]
@svanderburg what about patching `grunt`/`gulp` so that they correctly work with `NODE_PATH`? 

I have no idea what I'm talking about, by the way, I'm not familiar with `grunt`/`gulp`. Just thinking out loud.

**Comment by svanderburg** [comment]
Closing this. This is not a problem with the supplement feature, but a limitation of grunt/gulp in conjunction with `NODE_PATH` -- these tools don't respect this environment variable, and expect a `node_modules/` folder in the same base dir.

Unfortunately, in a shell session that folder can't be automatically created, because Nix is not allowed to make modifications outside the Nix store.
