### ISSUE TITLE
Node2nix 1.11.0 no longer builds the `result/bin` symlink, nor `result/lib/node_modules/.bin` symlinks

### ISSUE THREAD

**Issue by CMCDragonkai** [svanderburg/node2nix#293]
I'm comparing node2nix 1.11.0 to node2nix 1.9.0.

In the 1.9.0 version. The result of a simple JS application with a bin executable looks like this:

```
./result
├── bin -> lib/node_modules/.bin
└── lib
    └── node_modules
        ├── .bin
        │   └── dosomething -> ../somerandompackage/src/bin/dosomething.js
        └── somerandompackage
            ├── default.nix
            ├── .gitignore
            ├── nix
            │   └── leveldown.patch
            ├── package.json
            ├── .package.json.un~
            ├── package-lock.json
            ├── pkgs.nix
            ├── release.nix
            ├── shell.nix
            ├── src
            │   └── bin
            │       ├── dosomething.js
            │       ├── .dosomething.js.un~
            │       └── .dosomething.ts.un~
            ├── tsconfig.build.json
            ├── tsconfig.json
            ├── utils.nix
            ├── .utils.nix.swp
            └── .utils.nix.un~

8 directories, 18 files
```

Note the `./result/bin -> ./result/lib/node_modules/.bin` symlink AND also the `./result/lib/node_modules/.bin` directory containing the executable symlink `dosomething`.

With the exact same repository, using node2nix 1.11.0 (the master commit of this repository), the output is now:

```
./result
└── lib
    └── node_modules
        └── somerandompackage
            ├── default.nix
            ├── .gitignore
            ├── nix
            │   └── leveldown.patch
            ├── package.json
            ├── .package.json.un~
            ├── package-lock.json
            ├── pkgs.nix
            ├── release.nix
            ├── shell.nix
            ├── src
            │   └── bin
            │       ├── dosomething.js
            │       ├── .dosomething.js.un~
            │       └── .dosomething.ts.un~
            ├── tsconfig.build.json
            ├── tsconfig.json
            ├── utils.nix
            ├── .utils.nix.swp
            └── .utils.nix.un~

6 directories, 17 files
```

Notice how both the `bin` symlink is not there. Nor is the `.bin` directory under `./result/lib/node_modules`.

I believe the `bin` symlink is only created if the `./result/lib/node_modules/.bin` directory gets created.

However it appears the new way of using `npm install` (and npm has gone from 6.14.13 to 8.5.0), does not appear to create the `.bin` directory at all.

This means using node2nix on any JS application that has bin executables no longer builds.

**Comment by svanderburg** [comment]
Hmm this is a weird situation. I guess something may have changed recently, so that NPM thinks an executable folder has already been created.

I need to analyze the situation to find out the cause or find an alternative solution in which I create this `.bin` folder myself

**Comment by CMCDragonkai** [comment]
Yea, my duct-tape solution above allows me to move forward with node2nix 1.11.0.

However if you could shed light on:

> One thing I'm confused about is why npm install is used at all. In my duct-taped solution I just disabled it entirely with dontNpmInstall = true, and everything works fine.

Specifically:

https://github.com/svanderburg/node2nix/blob/node2nix-1.11.0/nix/node-env.nix#L380-L387

What exactly is that line expected to do? If the dependencies are already installed via nix, why run `npm install` again.

I've disabled it entirely and nothing has changed. Are there install hooks that are supposed to run?

**Comment by svanderburg** [comment]
NPM has two kinds of purposes -- so it does dependency management and build management (e.g. via script directives). It should skip the former aspects (because that conflicts with Nix), but still do the latter aspect.

In most NPM projects, there's no build management, but in some project there are.

I've just noticed the same problem. I guess some of my `package-lock.json` hacks could have caused this problem in newer versions of NPM.

I can either fix it by finding the conflicting property or manually create `bin/` symlinks.

**Comment by jtrees** [comment]
I just ran into this too. I'm still not that experienced with nix and I'm totally new to node2nix but let me know if I can help somehow.

**Comment by tstelzer** [comment]
I've been using `node2nix` as a way to use global npm executables (mostly language-servers), which seems to be broken now. Reading through the docs, I'm not even sure this is a supported use-case?

**Comment by andersk** [comment]
There was another discussion about this same issue at NixOS/nixpkgs#145432, where I concluded that the problem is a difference between NodeJS 14 to 16, not a difference between node2nix 1.9.0 and 1.11.0.

Some confounding factors that may have made it initially appear otherwise and made it generally more confusing to understand:

* node2nix 1.9.0 silently ignored `--nodejs-16` (#272).
* `nixpkgs.nodePackages` is defined with `.override { nodejs = nodejs-14_x; }` even though `nixpkgs.nodejs` is `nodejs-16_x`.
* Until recently, `nixpkgs.node2nix` used the 1.9.0 source even though its version was set to 1.10.0 (NixOS/nixpkgs#171195).

**Comment by CMCDragonkai** [comment]
Just a note, make sure to set executable permission flag on any files with shebang `#!/usr/bin/env node` so that nix rewrites those paths. Encountered that here: https://github.com/MatrixAI/js-polykey/pull/379#issuecomment-1168163847

**Comment by winterqt** [comment]
According to [the NPM docs](https://docs.npmjs.com/cli/v8/configuring-npm/folders), this folder structure is still in place as of the latest NPM version.

**Comment by winterqt** [comment]
Hi @svanderburg!

I believe I have figured out this issue, but before I can properly fix it, I need to know your reasoning behind something, if you don't mind: why does `buildNodePackage` create `$out/lib/node_modules` (but then include `node_modules` in `$out/lib/node_modules/${packageName}`?)

Basically, is this structure required for packages that create `$out/bin`, or not? Thanks!

**Comment by dbaynard** [comment]
Thanks @winterqt 

I've been toying with a workaround that adds the following after the call to `npm rebuild`.

```bash
    mkdir -p "$out/lib/node_modules/.bin"
    for i in $out/lib/node_modules/pnpm/bin/*; do
      local j="''${i##*/}"
      ln -sv "$i" "$out/lib/node_modules/.bin/''${j%.*}"
    done
```

This manually creates the folder that you found `npm` no longer creates.

I implemented this by patching `runHook postRebuild` into the `installPhase` (to complement `preRebuild`); would you consider adding something like that?

**Comment by RaitoBezarius** [comment]
Hi there, I just encountered this issue, @svanderburg would you be okay with one of the workaround above?

**Comment by lilyinstarlight** [comment]
@winterqt, digging deeper it seems npm does not install bins anymore for top-level projects unless you are doing a `--global` install (an undocumented breaking change that I had to dive into the npm code and `git blame` to find [when and where](https://github.com/npm/cli/commit/e46400c9484f5c66a0ba405eeb8c1340594dbf05#diff-24c01909dabbe2fc000fb5b43d14b511fb335b2f0c2e8e7a671f7d567a33d577R17-R18) it happened)

Does npm install the top-level project bins for you if you readjust the directory structure?

Could anyone also try and test #302? I believe I've fixed all of the issues (including this one) with Node.js 16+ / NPM v7+ in that PR

**Comment by winterqt** [comment]
@lilyinstarlight What do you mean by top-level in this case? Is that what the term is for trying to `npm install` in `node_modules/foo` and expecting `node_modules/.bin`? Not sure if I's call that top-level, seems a bit ambiguous.

**Comment by lilyinstarlight** [comment]
I'm not 100% because there is a lot of npm code, but yeah whatever directory you are running `npm install` from is what I mean (and what npm seems to call that in the code)
