### ISSUE TITLE
error: anonymous function at node-env.nix:3:1 called without required argument ‘python’, at default.nix:8:13

### ISSUE THREAD

**Issue by yorickvP** [svanderburg/node2nix#34]
I built the node2nix from this repo, the generated nix does not run (combined with latest nixos-unstable), see the error in the title.

**Comment by svanderburg** [comment]
I assume you have tried running the following command-line instruction:

```bash
$ nix-build default.nix -A build
```

I just tried building against latest master branch, but here it works.

**Comment by yorickvP** [comment]
Thanks, it seems that the node-env file isn't updated automatically, that's what happened.
