### ISSUE TITLE
v1.1.1 broke build

### ISSUE THREAD

**Issue by the-spyke** [svanderburg/node2nix#37]
My build machine started to fail, when I've updated node2nix to v1.1.1 from v1.1.0 with other packages.
`anonymous function at [.../node-env.nix[ called without required argument 'python2', at...` 
I think it's because of the commit "Explicitly refer to python2". Such changes shouldn't be in patch version by SemVer.

**Comment by svanderburg** [comment]
This is because node2nix never overwrites node-env.nix on regeneration. It may have been possible that an old node-env.nix tries to build a newer package set with incompatibilities.

In the current version of node2nix this has been solved.
