### ISSUE TITLE
sha1 -> sha256 due to proven forged collisions

### ISSUE THREAD

**Issue by jpierre03** [svanderburg/node2nix#39]
Due to recent collision on sha1 hash like http://thehackernews.com/2017/02/sha1-collision-attack.html :

1. can node2nix generate sha256 hash  ?
2. can node2nix generate sha256 hash  even if upstream provide sha1 (https://github.com/npm/npm/issues/4938) ?

https://github.com/svanderburg/node2nix/blob/8acaa08fd412738e326a4a1cbfcbfcb1d75ba2be/lib/packagefetcher/npmregistry.js#L95

**Comment by svanderburg** [comment]
Yes 1 and 2 are both possible. Instead of taking the sha1 value from the registry, we can simply take the tarball ourselves and compute the corresponding sha256 hash.

I hope, however, that NPM comes with a solution instead of becoming responsible for this issue myself.

**Comment by svanderburg** [comment]
It seems that for new packages that get published the registry will provide both an sha1 and sha512 option.

I have modify node2nix in such a way that if the sha512 is present, it will use that instead of sha1

**Comment by svanderburg** [comment]
Revision 1ae1e9ca290221ae46e1774097819177969be43c computes sha512 for those packages providing it.

**Comment by jpierre03** [comment]
Nice one.
So now it's up to NPM to provide sha512 hashs for all packages.

Looks acceptable to close this issue.
