### ISSUE TITLE
Node2nix only generates node-env.nix if it does not exit

### ISSUE THREAD

**Issue by pindexis** [svanderburg/node2nix#42]
Node2nix only generates node-env.nix if it does not exit, but call it with different parameters in version 1.2 , replacing python by python2 wich yields an exception.
Is Node-env.nix is supposed to be generated? if so, I'm curious why not overwriting it, since it seems like it's intentional behavior
https://github.com/svanderburg/node2nix/blob/master/lib/node2nix.js#L114
FYI @rbvermaa

**Comment by svanderburg** [comment]
There are some cases in which you don't want that to happen (say, when you want to use node-env.nix among several projects or a custom implementation).

But I think you're right in the sense that it is quite confusing. Maybe I should make the default behaviour to overwrite node-env.nix and a new command-line option that can be used to prevent that from happening.

**Comment by svanderburg** [comment]
I changed the behaviour in revision 5c612f116a20a12ac8338bd45afcfea25cdc1cf2 to overwrite node-env.nix. Additionally, it can prevented from being copied by passing the `--no-copy-node-env` command line parameter.

**Comment by pindexis** [comment]
thank you @svanderburg . I'm wondering how to use node-env.nix among several projects. it seems that the command-line accepts only one package.json as an option.
