### ISSUE TITLE
node2nix fails with ssh+git url in package.json

### ISSUE THREAD

**Issue by coltfred** [svanderburg/node2nix#43]
I'm attempting to convert a package.json file using node2nix and I'm receiving an error.

I have the following in my dependencies list:
```
xxxx: git+ssh://git@github.com/IronCoreLabs/xxxx.git
```
where xxxx is a private repo.

Then I ran `node2nix -6 -i package.json` which exits with an error and the following output:

```
HEAD is now at b5863b5... Merge pull request #5 from XXXXXXX
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn nix-hash ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
If I remove the git dependency, the node2nix process completes successfully. Let me know if there is any more information you'd like about the situation.

**Comment by svanderburg** [comment]
It looks like this problem is caused by the absence of the `nix-hash` executable in your PATH? Do you also have the Nix package manager installed?

**Comment by coltfred** [comment]
@svanderburg Ugh, you're right. I was in an *old* shell apparently. When I opened a new shell the command was found. I didn't equate that message with the nix-hash not being found, though now that I read it more carefully I probably should have tried it.

Is there a way to make that kind of error message better?

**Comment by coltfred** [comment]
I'm gonna close this, as it was my fault. Thank you so much @svanderburg.
