### ISSUE TITLE
Could use a warning when package.json is missing the version field

### ISSUE THREAD

**Issue by Ptival** [svanderburg/node2nix#48]
In practice, what happens is everything gets generated, but then commands like:
```
nix-shell -A shell
```
fail because the argument `version` does not get passed around.

As a beginner, it was not obvious what the issue was.

**Comment by svanderburg** [comment]
I have added a check for this in 04b00adb2f2655afb1f7ef08125932052fc19d8a

Will be included in the upcoming version.
