### ISSUE TITLE
Sorting sources and dependencies

### ISSUE THREAD

**Issue by orivej** [svanderburg/node2nix#69]
Currently after adding a package to `node-packages.json` (in Nixpkgs) and regenerating, sources and dependencies in `node-packages.nix`  are not only updated but also shuffled (moved before or after their previous neighbors). This increases the diff, which makes it hard to look at and needlessly grows the size of repository. I think that the set of sources and lists of dependencies should be sorted to prevent this.

**Comment by svanderburg** [comment]
Yes, that would not be such a bad idea. After all, we prefer determinism.

**Comment by svanderburg** [comment]
Just implemented this in revision caf5d68f4a5dcbbcf70ef2f2d0cd26a2aeae7b97
