### ISSUE TITLE
pnpm?

### ISSUE THREAD

**Issue by wmertens** [svanderburg/node2nix#79]
I just stumbled on https://pnpm.js.org/ - it uses a nice mix of symlinks and hardlinks to install deps, and seems to work properly for most packages.

It actually seems already quite a long way towards nix - the modules are stored separately in a cache and then combined in the project.

Maybe some ideas from there can be used here, or we can add the option to use the nix store in there.

They are using hardlinks to copy the modules in place, so to keep the original modules in the store they should either be mentioned in some file, or the hardlinks should be symlinks.

**Comment by adisbladis** [comment]
I while back I started a separate project for this: https://github.com/adisbladis/pnpm2nix/

**Comment by onetom** [comment]
`pnpm` was actually working until recently, like:

```sh
nix-shell -p nodePackages_8_x.pnpm
```

so I think this issue can be closed.

It currently fails, but that might be unrelated to `node2nix`.
If it's related, it should be a separate issue.
```
./pnpm/lib/node_modules/buffer/bin/download-node-tests.js: interpreter directive changed from "/usr/bin/env node" to "/nix/store/2wm0059s37nmyqb0qxlsdmcj0d4hlf2a-nodejs-8.12.0/bin/node"
./pnpm/lib/node_modules/tree-kill/cli.js: interpreter directive changed from "/usr/bin/env node" to "/nix/store/2wm0059s37nmyqb0qxlsdmcj0d4hlf2a-nodejs-8.12.0/bin/node"
No package-lock.json file found, reconstructing...
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:../../privatePackages/assert-project

npm ERR! A complete log of this run can be found in:
npm ERR!     /private/var/folders/sp/dp9j0mxs3b3c_3g6sfs_7qwm0000gn/T/nix-build-node-pnpm-2.18.2.drv-0/.npm/_logs/2018-11-26T05_47_44_227Z-debug.log
builder for '/nix/store/9bbcavn00awfrdcfp5ahh0a48y3ybidj-node-pnpm-2.18.2.drv' failed with exit code 1
error: build of '/nix/store/9bbcavn00awfrdcfp5ahh0a48y3ybidj-node-pnpm-2.18.2.drv' failed
```

**Comment by srghma** [comment]
issue mentioned at https://github.com/svanderburg/node2nix/issues/79#issuecomment-441526589 is fixed

**Comment by svanderburg** [comment]
Closing this, because the corresponding pnpm issue was fixed.
