### ISSUE TITLE
Wrong relative paths if one runs the script in other directory than project directory and pass in and out paths explicitly.

### ISSUE THREAD

**Issue by srghma** [svanderburg/node2nix#83]
Namely: removing `cd ../grunt` in [this commit](https://github.com/svanderburg/node2nix/commit/99f7a85b49ea5d50417ad0a85417276bd4ca4442) changed output paths [here](https://github.com/svanderburg/node2nix/commit/99f7a85b49ea5d50417ad0a85417276bd4ca4442#diff-5ee9cbbb8389bfe2cc3a345d426d27f2L8) and [here](https://github.com/svanderburg/node2nix/commit/99f7a85b49ea5d50417ad0a85417276bd4ca4442#diff-7073abb90898a889df92ce88f745e99eL390)

How to reproduce

Changing
 
```sh
cd grunt
 node ../../bin/node2nix -d -i package.json --supplement-input supplement.json -e ../../nix/node-env.nix --no-copy-node-env
```
to

```sh
node $PROJECT/bin/node2nix \
  -d \
  -i $PROJECT/tests/grunt/package.json \
  -o $PROJECT/tests/grunt/node-packages.nix \
  -c $PROJECT/tests/grunt/default.nix \
  --supplement-input $PROJECT/tests/grunt/supplement.json \
  --supplement-output $PROJECT/tests/grunt/supplement.nix \
  -e $PROJECT/nix/node-env.nix \
  --no-copy-node-env
```

generates 
https://github.com/svanderburg/node2nix/commit/99f7a85b49ea5d50417ad0a85417276bd4ca4442#diff-5ee9cbbb8389bfe2cc3a345d426d27f2R8
and 
https://github.com/svanderburg/node2nix/commit/99f7a85b49ea5d50417ad0a85417276bd4ca4442#diff-7073abb90898a889df92ce88f745e99eR390

instead of 

https://github.com/svanderburg/node2nix/commit/99f7a85b49ea5d50417ad0a85417276bd4ca4442#diff-5ee9cbbb8389bfe2cc3a345d426d27f2L8 
and 
https://github.com/svanderburg/node2nix/commit/99f7a85b49ea5d50417ad0a85417276bd4ca4442#diff-7073abb90898a889df92ce88f745e99eL390

**Comment by svanderburg** [comment]
Closing this, since the new release contains this fix.
