### ISSUE TITLE
Packaging tslint fails because "typescript" dependency isn't found

### ISSUE THREAD

**Issue by pmiddend** [svanderburg/node2nix#89]
I tried to create a nix derivation for "tslint" (see [here](https://www.npmjs.com/package/tslint)) using just `["tslint"]` as my `node-packages.json` file. I was able to `nix-build` the thing, but when starting it, it says it cannot find the `typescript` module. And indeed, the `dependencies` of tslint don't include `typescript`. If I manually add it, I can start `tslint` just fine. But why is it missed?

**Comment by svanderburg** [comment]
I just checked the `package.json` configuration of the tslint package and it seems that `typescript` has been declared a *peer* dependency -- originally, peer dependencies were installed as regular runtime dependencies with NPM, but this behaviour has changed with NPM versions newer than 2.x.

In newer versions of NPM, it merely serves as a conflict check. As a result, if it is not declared as a normal dependency it won't be installed.

`node2nix` also follows the behaviour of newer versions of NPM by default. However, there is an option that you can use to replicate the old behaviour:

```bash
$ node2nix --include-peer-dependencies
```

then I guess it should work.

I also checked `tslint` by installing it with NPM myself, and in this case `typescript` does not install.

**Comment by pmiddend** [comment]
Wow, thanks for the excellent detective work. I thought about including `tslint` in nixpkgs, but this makes it more difficult I think. Anyway, this can be closed.
