### ISSUE TITLE
Install instructions not working

### ISSUE THREAD

**Issue by joehenry087** [svanderburg/node2nix#9]
I have nix installed, and the only channel I'm subscribed to is the default nixpkgs-unstable.

Running the install command "nix-env -f '<nixpkgs>' -iA nodePackages.node2nix" results in this error:

error: attribute ‘node2nix’ in selection path ‘nodePackages.node2nix’ not found

Are there more steps to the install that I'm missing?

**Comment by svanderburg** [comment]
No, it's indeed broken. I will update the upstream Nixpkgs asap, so that this will work again.

Meanwhile, you can still install the package, by cloning the git repo and running:

```bash
$ nix-env -f default.nix -iA package
```

**Comment by svanderburg** [comment]
The current master branch of Nixpkgs provides node2nix as a package, so it's fixed now
