### ISSUE TITLE
Using node-9_x package

### ISSUE THREAD

**Issue by Rizary** [svanderburg/node2nix#96]
Will there be an update on using node-9_x as its args? I mean if I am willing to help, would you mind to pointing me to the right direction? @svanderburg

**Comment by svanderburg** [comment]
When you invoke `node2nix` with a version flag, e.g. `node2nix -8`, it is simply a shorthand for the following command:

```bash
$ node2nix --flatten --bypass-cache --pkg-name nodejs-8_x
```

What you can do for Node.js 9.x is invoke it with the same settings but a different package name:

```bash
$ node2nix --flatten --bypass-cache --pkg-name nodejs-9_x
```

**Comment by svanderburg** [comment]
I assume this clarifies the question
